### ISSUE TITLE
Task 1

### ISSUE THREAD

**Issue by DaveSaah** [Surviving-with-Google/problem-solving-practice#1]
Using **Problem Definition & Analysis**, break down the following problems.

1. Python program to find out the average of a set of integers.
2. Python program to find the area of a triangle whose sides are given.

**Comment by DaveSaah** [comment]
## Follow this for answering
Q_no

**Understanding of problem**
Your explanation

**Requirements**
Your explanation

**Boundaries**
Your explanation

**Output**
Your explanation

Q_no....

**Comment by Abugatwin** [comment]
Q1.
**understanding  of the problem**
write python program that can calculate the average of series of integers .

**Requirements**
I need to know the formula for calculating the average of numbers .
Average =(n+ n+ n+ n+ n)/5

**Boundaries** 
The integers can be any numbers, since the problem did not given specific integers.

**Output**
The program should be able to calculate the average of any series of  integers without errors.

Q2.
**Understanding of the problem**
Write python program that can calculate the area of a triangle that the sides are given.

**Requirements** 
I need the formula for calculating the area of triangle whose sides are given
Area(A) =( s(s-a)(s-b)(s-c))^0.5
where s is the semi-perimeter =(a+ b+ c)/2

**Boundaries** 
s,a,b,c can be any number in this particular problem, since there are no numbers assigned to them.

**Output**
The program should be able to calculate the area at any given number of s, a, b, and c.

**Comment by DaveSaah** [comment]
> Q1. **understanding of the problem** write python program that can calculate the average of series of integers .
> 
> **Requirements** I need to know the formula for calculating the average of numbers . Average =(n+ n+ n+ n+ n)/5
> 
> **Boundaries** The integers can be any numbers, since the problem did not give specific integers.
> 
> **Output** The program should be able to calculate the average of any series of integers without errors.
> 
> Q2. **Understanding of the problem** Write python program that can calculate the area of a triangle that the sides are given.
> 
> **Requirements** I need the formula for calculating the area of triangle whose sides are given Area(A) =( s(s-a)(s-b)(s-c))^0.5 where s is the semi-perimeter =(a+ b+ c)/2
> 
> **Boundaries** s,a,b,c can be any number in this particular problem, since there are no numbers assigned to them.
> 
> **Output** The program should be able to calculate the area at any given number of s, a, b, and c.


That's great 👏. You did a good job breaking down the problems to understand what the requirements, boundaries and output are. 
With more practice, you'll be able to break down more complex problems. 
Good job 👍
